-- ====================================================================
-- Department of Zoology — Banaras Hindu University
-- Supabase Storage & Database Setup Script
-- Project Hosting: GitHub Pages
-- ====================================================================

-- 1. Create 'study-materials' Storage Bucket (Public with 25MB limit)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'study-materials',
  'study-materials',
  true,
  26214400, -- 25 MB in bytes
  array[
    'application/pdf',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do update set
  public = true,
  file_size_limit = 26214400;

-- 2. Storage Objects RLS Policies for 'study-materials'
-- Drop existing policies if any exist to prevent duplicate errors
drop policy if exists "Public Access to study-materials" on storage.objects;
drop policy if exists "Public Uploads to study-materials" on storage.objects;
drop policy if exists "Public Updates to study-materials" on storage.objects;
drop policy if exists "Public Deletes on study-materials" on storage.objects;

-- Allow anyone (public / anonymous / students) to read & download files from the bucket
create policy "Public Access to study-materials"
  on storage.objects for select
  using ( bucket_id = 'study-materials' );

-- Allow students to upload study materials into the 'study-materials' bucket
create policy "Public Uploads to study-materials"
  on storage.objects for insert
  with check ( bucket_id = 'study-materials' );

-- Allow update if needed
create policy "Public Updates to study-materials"
  on storage.objects for update
  using ( bucket_id = 'study-materials' );

-- Allow deletion if needed
create policy "Public Deletes on study-materials"
  on storage.objects for delete
  using ( bucket_id = 'study-materials' );

-- 3. Create 'materials' Table with all required metadata columns
create table if not exists public.materials (
  id text primary key default gen_random_uuid()::text,
  title text not null,
  subject text not null,
  semester text not null,
  uploader_name text not null,
  file_path text not null,
  public_url text not null,
  file_type text not null,
  file_size bigint not null default 0,
  created_at timestamptz not null default now(),

  -- Frontend bookshelf compatibility columns
  paper text,
  topic text default 'General',
  type text,
  student text,
  date text,
  description text,
  file text,
  image text,
  views integer default 1,
  likes integer default 0
);

-- Enable RLS on 'materials' table
alter table public.materials enable row level security;

-- Policies for public.materials
drop policy if exists "Allow public select on materials" on public.materials;
drop policy if exists "Allow public insert on materials" on public.materials;
drop policy if exists "Allow public update on materials" on public.materials;
drop policy if exists "Allow public delete on materials" on public.materials;

create policy "Allow public select on materials"
  on public.materials for select
  using (true);

create policy "Allow public insert on materials"
  on public.materials for insert
  with check (true);

create policy "Allow public update on materials"
  on public.materials for update
  using (true);

create policy "Allow public delete on materials"
  on public.materials for delete
  using (true);

-- 4. Create 'visitors' Table for honest visitor counter
create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  visited_at timestamptz not null default now(),
  session_id text
);

alter table public.visitors enable row level security;

drop policy if exists "Allow public select on visitors" on public.visitors;
drop policy if exists "Allow public insert on visitors" on public.visitors;

create policy "Allow public select on visitors"
  on public.visitors for select
  using (true);

create policy "Allow public insert on visitors"
  on public.visitors for insert
  with check (true);
