-- ====================================================================
-- Department of Zoology — Banaras Hindu University
-- Supabase Storage & Database Setup Script
-- Project Hosting: GitHub Pages
-- ====================================================================

-- 1. Create 'study-materials' Storage Bucket (Public with 25MB limit)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'study-materials',
  'study-materials',
  true,
  26214400, -- 25 MB in bytes
  array[
    'application/pdf',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do update set
  public = true,
  file_size_limit = 26214400;

-- 2. Storage Objects RLS Policies for 'study-materials'
drop policy if exists "Public Access to study-materials" on storage.objects;
drop policy if exists "Public Uploads to study-materials" on storage.objects;
drop policy if exists "Public Updates to study-materials" on storage.objects;
drop policy if exists "Public Deletes on study-materials" on storage.objects;

-- Allow anyone to read & download files from the bucket
create policy "Public Access to study-materials"
  on storage.objects for select
  using ( bucket_id = 'study-materials' );

-- Allow students to upload study materials into the 'study-materials' bucket
create policy "Public Uploads to study-materials"
  on storage.objects for insert
  with check ( bucket_id = 'study-materials' );

create policy "Public Updates to study-materials"
  on storage.objects for update
  using ( bucket_id = 'study-materials' );

create policy "Public Deletes on storage study-materials" on storage.objects for delete
  using ( bucket_id = 'study-materials' );

-- 3. Create 'materials' Table with exact canonical column names
create table if not exists public.materials (
  id text primary key default gen_random_uuid()::text,
  title text not null,
  paper text not null,
  semester text not null,
  topic text not null default 'General',
  type text not null default 'PDF',
  student text not null,
  date text not null default to_char(now(), 'YYYY-MM-DD'),
  description text default '',
  file text default '',
  image text default '',
  views integer default 0,
  likes integer default 0,
  created_at timestamptz not null default now()
);

-- Ensure columns exist in case table was pre-existing
alter table public.materials add column if not exists title text;
alter table public.materials add column if not exists paper text;
alter table public.materials add column if not exists semester text;
alter table public.materials add column if not exists topic text default 'General';
alter table public.materials add column if not exists type text default 'PDF';
alter table public.materials add column if not exists student text;
alter table public.materials add column if not exists date text default to_char(now(), 'YYYY-MM-DD');
alter table public.materials add column if not exists description text default '';
alter table public.materials add column if not exists file text default '';
alter table public.materials add column if not exists image text default '';
alter table public.materials add column if not exists views integer default 0;
alter table public.materials add column if not exists likes integer default 0;
alter table public.materials add column if not exists created_at timestamptz default now();

-- Enable RLS on 'materials' table
alter table public.materials enable row level security;

-- Policies for public.materials
drop policy if exists "Allow public select on materials" on public.materials;
drop policy if exists "Allow public insert on materials" on public.materials;
drop policy if exists "Allow public update on materials" on public.materials;
drop policy if exists "Allow public delete on materials" on public.materials;

create policy "Allow public select on materials"
  on public.materials for select
  using (true);

create policy "Allow public insert on materials"
  on public.materials for insert
  with check (true);

create policy "Allow public update on materials"
  on public.materials for update
  using (true);

create policy "Allow public delete on materials"
  on public.materials for delete
  using (true);

-- 4. Create 'visitors' Table for honest visitor counter
create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  visited_at timestamptz not null default now(),
  session_id text
);

alter table public.visitors enable row level security;

drop policy if exists "Allow public select on visitors" on public.visitors;
drop policy if exists "Allow public insert on visitors" on public.visitors;

create policy "Allow public select on visitors"
  on public.visitors for select
  using (true);

create policy "Allow public insert on visitors"
  on public.visitors for insert
  with check (true);
