-- ====================================================================
-- Department of Zoology — Banaras Hindu University
-- Supabase Migration: Fix Materials Schema & Column Alignment
-- ====================================================================

-- 1. Ensure 'materials' table exists with exact canonical column names
create table if not exists public.materials (
  id text primary key default gen_random_uuid()::text,
  title text not null,
  paper text not null,
  semester text not null,
  topic text not null default 'General',
  type text not null default 'PDF',
  student text not null,
  date text not null default to_char(now(), 'YYYY-MM-DD'),
  description text default '',
  file text default '',
  image text default '',
  views integer default 0,
  likes integer default 0,
  created_at timestamptz not null default now()
);

-- 2. Add any missing columns to existing tables (safe idempotent migrations)
alter table public.materials add column if not exists title text;
alter table public.materials add column if not exists paper text;
alter table public.materials add column if not exists semester text;
alter table public.materials add column if not exists topic text default 'General';
alter table public.materials add column if not exists type text default 'PDF';
alter table public.materials add column if not exists student text;
alter table public.materials add column if not exists date text default to_char(now(), 'YYYY-MM-DD');
alter table public.materials add column if not exists description text default '';
alter table public.materials add column if not exists file text default '';
alter table public.materials add column if not exists image text default '';
alter table public.materials add column if not exists views integer default 0;
alter table public.materials add column if not exists likes integer default 0;
alter table public.materials add column if not exists created_at timestamptz default now();

-- Optional auxiliary metadata columns for extended storage audit
alter table public.materials add column if not exists file_path text;
alter table public.materials add column if not exists file_size bigint default 0;
alter table public.materials add column if not exists file_type text;
alter table public.materials add column if not exists public_url text;

-- 3. Enable Row Level Security (RLS)
alter table public.materials enable row level security;

-- Idempotent RLS Policies for public access (Department of Zoology open repository)
drop policy if exists "Allow public select on materials" on public.materials;
drop policy if exists "Allow public insert on materials" on public.materials;
drop policy if exists "Allow public update on materials" on public.materials;
drop policy if exists "Allow public delete on materials" on public.materials;

create policy "Allow public select on materials"
  on public.materials for select
  using (true);

create policy "Allow public insert on materials"
  on public.materials for insert
  with check (true);

create policy "Allow public update on materials"
  on public.materials for update
  using (true);

create policy "Allow public delete on materials"
  on public.materials for delete
  using (true);

-- 4. Create and configure 'study-materials' Storage Bucket
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'study-materials',
  'study-materials',
  true,
  26214400, -- 25 MB in bytes
  array[
    'application/pdf',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do update set
  public = true,
  file_size_limit = 26214400;

-- Storage Objects Policies for 'study-materials' bucket
drop policy if exists "Public Access to study-materials" on storage.objects;
drop policy if exists "Public Uploads to study-materials" on storage.objects;
drop policy if exists "Public Updates to study-materials" on storage.objects;
drop policy if exists "Public Deletes on study-materials" on storage.objects;

create policy "Public Access to study-materials"
  on storage.objects for select
  using ( bucket_id = 'study-materials' );

create policy "Public Uploads to study-materials"
  on storage.objects for insert
  with check ( bucket_id = 'study-materials' );

create policy "Public Updates to study-materials"
  on storage.objects for update
  using ( bucket_id = 'study-materials' );

create policy "Public Deletes on study-materials"
  on storage.objects for delete
  using ( bucket_id = 'study-materials' );

-- 5. Visitor counter table
create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  visited_at timestamptz not null default now(),
  session_id text
);

alter table public.visitors enable row level security;

drop policy if exists "Allow public select on visitors" on public.visitors;
drop policy if exists "Allow public insert on visitors" on public.visitors;

create policy "Allow public select on visitors"
  on public.visitors for select
  using (true);

create policy "Allow public insert on visitors"
  on public.visitors for insert
  with check (true);
